/* eslint-disable import/prefer-default-export */
export const newReleaseTitles = [
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/random-acts-of-violence-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/random-acts-of-violence-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/redemption-day-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/redemption-day-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/silk-road-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/silk-road-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-last-vermeer-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-last-vermeer-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-croods-a-new-age-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-croods-a-new-age-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/centigrade-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/centigrade-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/scooby-doo-the-sword-and-the-scoob-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/scooby-doo-the-sword-and-the-scoob-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/collective-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/collective-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-swordsman-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/the-swordsman-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/a-call-to-spy-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/a-call-to-spy-cover.jpg',
  },
  {
    original:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/a-call-to-spy-cover.jpg',
    thumbnail:
      'https://bendblockbuster.com/wp-content/uploads/2021/02/a-call-to-spy-cover.jpg',
  },
];
